# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version From Github to the Google Play Internal Test"
  lane :distribute_app_store do
    upload_to_play_store(track:"internal", release_status:"draft", aab:"../build/app/outputs/bundle/release/app-release.aab", json_key:"play_store.key")
  end
  desc "Deploy a new version to the Google Play Internal Test"
  lane :deploy do
    upload_to_play_store(track:"internal", release_status:"draft", aab:"../build/app/outputs/bundle/release/app-release.aab")
  end

  desc "Upload Android App to Firebase"
  lane :distribute_android_app do
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID_ANDROID"],
          testers: "dglvalerio@gmail.com",
          release_notes: "Lots of amazing new features to test out!",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
          service_credentials_file: "firebase_musdoo_credentials.json"
      )
  end

end
